# Generated by Django 2.1.7 on 2019-05-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
